### ISSUE TITLE
Building array of single-element arrays in `GDPpcProvider.get_iso_timeseries()` with numpy>=1.14

### ISSUE THREAD

**Issue by brews** [ClimateImpactLab/impact-common#5]
With newer versions of numpy (>= 1.14) `GDPpcProvider.get_iso_timeseries()` returns a numpy array filled with single-element numpy arrays.

This problem is based here and in the proceeding for-loop:  https://github.com/ClimateImpactLab/impact-common/blob/2a62cd2616ccb88ac643ec9082ded4fa274830ec/impactcommon/exogenous_economy/gdppc.py#L90 

The problem causes an error downstream in `impact-calculations` when code tries to take the log of this object-array. Here is an example traceback from an energy diagnostic run:

```
Traceback (most recent call last):
  File "/home/bmalevich/miniconda3/envs/impactprojection-py27-TEST/bin/impactprojection", line 10, in <module>
    sys.exit(impactcalculations_cli())
  File "/home/bmalevich/miniconda3/envs/impactprojection-py27-TEST/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/bmalevich/miniconda3/envs/impactprojection-py27-TEST/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/bmalevich/miniconda3/envs/impactprojection-py27-TEST/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/bmalevich/miniconda3/envs/impactprojection-py27-TEST/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bmalevich/miniconda3/envs/impactprojection-py27-TEST/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/bmalevich/miniconda3/envs/impactprojection-py27-TEST/lib/python2.7/site-packages/cli/__init__.py", line 57, in diagnostic
    gg.main(file_configs)
  File "/home/bmalevich/miniconda3/envs/impactprojection-py27-TEST/lib/python2.7/site-packages/generate/generate.py", line 200, in main
    mod.produce(targetdir, weatherbundle, economicmodel, pvals, config, push_callback=lambda *args: genericpush_callback(*args, weatherbundle=weatherbundle, economicmodel=economicmodel), diagnosefile=os.path.join(targetdir, shortmodule + "-allcalcs.csv"))
  File "/home/bmalevich/miniconda3/envs/impactprojection-py27-TEST/lib/python2.7/site-packages/interpret/container.py", line 77, in produce
    produce_csvv(basename, csvvpath, module, specconf, targetdir, weatherbundle, economicmodel, pvals, configs.merge(config, model), push_callback, suffix, profile, diagnosefile)
  File "/home/bmalevich/miniconda3/envs/impactprojection-py27-TEST/lib/python2.7/site-packages/interpret/container.py", line 104, in produce_csvv
    calculation, dependencies, baseline_get_predictors = caller.call_prepare_interp(csvv, module, weatherbundle, economicmodel, pvals[basename], specconf=specconf, config=config, standard=False)
  File "/home/bmalevich/miniconda3/envs/impactprojection-py27-TEST/lib/python2.7/site-packages/generate/caller.py", line 83, in call_prepare_interp
    calculation, dependencies, baseline_get_predictors = mod.prepare_interp_raw(csvv, weatherbundle, economicmodel, pvals, farmer, **kwargs)
  File "/home/bmalevich/miniconda3/envs/impactprojection-py27-TEST/lib/python2.7/site-packages/interpret/calcspec.py", line 14, in prepare_interp_raw
    covariator = specification.create_covariator(specconf, weatherbundle, economicmodel, config, quiet=config.get('quiet', False))
  File "/home/bmalevich/miniconda3/envs/impactprojection-py27-TEST/lib/python2.7/site-packages/interpret/specification.py", line 47, in create_covariator
    covariators.append(get_covariator(covar, None, weatherbundle, economicmodel, config=fullconfig, quiet=quiet))
  File "/home/bmalevich/miniconda3/envs/impactprojection-py27-TEST/lib/python2.7/site-packages/interpret/specification.py", line 20, in get_covariator
    return get_covariator(covar.keys()[0], covar.values()[0], weatherbundle, economicmodel, config=config, quiet=quiet)
  File "/home/bmalevich/miniconda3/envs/impactprojection-py27-TEST/lib/python2.7/site-packages/interpret/specification.py", line 24, in get_covariator
    return covariates.BinnedEconomicCovariator(economicmodel, 2015, args, config=configs.merge(config, 'econcovar'))
  File "/home/bmalevich/miniconda3/envs/impactprojection-py27-TEST/lib/python2.7/site-packages/adaptation/covariates.py", line 105, in __init__
    super(BinnedEconomicCovariator, self).__init__(economicmodel, maxbaseline, config=config)
  File "/home/bmalevich/miniconda3/envs/impactprojection-py27-TEST/lib/python2.7/site-packages/adaptation/covariates.py", line 46, in __init__
    self.econ_predictors = economicmodel.baseline_prepared(maxbaseline, self.numeconyears, lambda values: averages.interpret(config, standard_economic_config, values))
  File "/home/bmalevich/miniconda3/envs/impactprojection-py27-TEST/lib/python2.7/site-packages/adaptation/econmodel.py", line 71, in baseline_prepared
    econ_predictors[region] = dict(loggdppc=func(np.log(baseline_gdppcs)), popop=func([popop]))
AttributeError: 'numpy.float64' object has no attribute 'log'

```

Currently a workaround is to pin the work environment to numpy=1.14.

**Comment by brews** [comment]
A think a quick fix is to ensure that we use `np.asscalar()` on any items we append back to the `gdppcs` list (e.g. https://github.com/ClimateImpactLab/impact-common/blob/2a62cd2616ccb88ac643ec9082ded4fa274830ec/impactcommon/exogenous_economy/gdppc.py#L88). Edit: Looks like `np.asscalar() is deprecated in favor of `.item()`.

Might also use `np.stack()` or `np.concatenate()` instead of `np.array()` here: https://github.com/ClimateImpactLab/impact-common/blob/2a62cd2616ccb88ac643ec9082ded4fa274830ec/impactcommon/exogenous_economy/gdppc.py#L90

Not sure which is the most robust solution because I don't know what the usecases are.

**Comment by brews** [comment]
Yo, @jrising, is `GDPpcProvider.get_iso_timeseries()` supposed to return a 1D array of floats?
